### PR TITLE
rse: add case studies

### PR DESCRIPTION
**Pull request by rkdarst**
- Someone suggested that "case studies" would be a good way to
  introduce what the program can do, rather than long texts.  Add them
  for researchers and units.
- Review: check if these are representative of what we do and somewhat
  correct in wording.

### CODE REVIEW

**Review by wmvanvliet — COMMENTED** [review]
Love the first two use cases. For the third, I think RSEs can do more than just introduce Git. We can also help structure the codebase. Refractor stuff that is used across projects into into a lib with a good API. Etc.

**Comment by eglerean** [comment]
Added a case about sustainability of old projects

**Comment by rantahar** [comment]
I like all of these and they cover most important cases. The one @wmvanvliet mentions, building a library/api out of code from one or more projects, could be added as a separate use case.

**Review by wmvanvliet — APPROVED** [review]
I like the use cases this way!

**Comment by rkdarst** [comment]
I will merge this so I can send it to someone, we can always continue to improve.

I was also wondering about the balance between case studies and the list below (to avoid having the page become too long), but it seems good now.

**Pull request merged**
