### PR TITLE
Exporter Plugins and Late Submission Policy Documentation

### PR DESCRIPTION
**Pull request by AlirezaT99**

### CODE REVIEW

**Review by rkdarst — COMMENTED** [review]
I had written these before but put never pushed the "comment" button so they were all held as pending.  Pushing now and will re-read later.

**Review by rkdarst — APPROVED** [review]
This is looking good to me.  I'd say it can be merged now and iterated, but it's also OK to keep working on it if you want.  Remember to look at/possibly accept the suggestions I gave.

**Comment by AlirezaT99** [comment]
> This is looking good to me. I'd say it can be merged now and iterated, but it's also OK to keep working on it if you want. Remember to look at/possibly accept the suggestions I gave.

Thanks for your review. I was postponing this to make sure DetailedExporter works first.

**Comment by rkdarst** [comment]
This can be done now, right?

**Comment by AlirezaT99** [comment]
@rkdarst Yes. Except for the grant extension section which is not merged yet.

**Comment by rkdarst** [comment]
I just saw this is still open... I'll merge now.

**Pull request merged**
