### PR TITLE
More links!

### PR DESCRIPTION
**Pull request by eglerean**
Adding more courses not organized by us. Adding registration links that were missing.

### CODE REVIEW

**Review by rkdarst — APPROVED** [review]

**Comment by rkdarst** [comment]
While doing this big revision, should hands-on scicomp be more mentioned and integrated somehow?  Like, 'here is a basic outline, our courses are ..."?

**Comment by eglerean** [comment]
yes! Even with a picture of the HoSC roadmap embeded in the /training/ page for example and a link to the Aplus too maybe?

**Comment by rkdarst** [comment]
Yeah, good idea.  Perhaps now the picture could be improved (I wasn't
very good at making it).  The story is good but by now it could be
revised to make it more clear and user-centric, too.

**Comment by eglerean** [comment]
I have added the image and local build looks good. I merge and then we can revise

**Pull request merged**
